openapi: 3.0.0
x-stoplight:
  id: dmiy7jxs5yhc4
info:
  title: todo-app
  version: '1.0'
servers:
  - url: 'http://localhost:3100'
paths:
  '/tasks/{taskId}':
    parameters:
      - schema:
          type: string
        name: taskId
        in: path
        required: true
    get:
      summary: タスク詳細を取得する
      tags:
        - tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  description:
                    type: string
                    nullable: true
                  status:
                    type: string
                  status_id:
                    type: number
                required:
                  - id
                  - name
                  - description
                  - status
                  - status_id
      operationId: get-tasks-taskId
    put:
      summary: タスクを更新する
      tags:
        - tasks
      responses:
        '204':
          description: No Content
      operationId: put-tasks-taskId
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                status_id:
                  type: number
              required:
                - name
                - status_id
components:
  schemas: {}
